### PR TITLE
Quick fix branch for recents

### LINKED ISSUE #1: Cleanup Layout file and move components to block
- So they will be under `app/components/blocks/layout/sidebar`
- also move the `header` into the `layout` block
- SideNav should reflect the Icons and Menu Items of the previous version of the App
- SideNav active link should work (read more on [Remix](https://remix.run/docs/en/main/hooks/use-location))
- Change the Logo to the correct Logo
- Profile Dropdown data should be extract into an object (`app/components/blocks/layout/profile-dropdown`)

### LINKED ISSUE #2: Fix the Dashboard (home page)
- The table is Broken
- The data from the table should be abstracted outside
- The button on the table is broken
- The data in the right panel should be extracted

### LINKED ISSUE #3: Fix the UI for showing User Details
Screenshot 2024-06-03 at 11 35 46 PM

### LINKED ISSUE #4: Add Language Dropdown according to Design
Screenshot 2024-06-03 at 11 36 52 PM

### PR DESCRIPTION
**Pull request by glenmiracle18**
Quick updates and rearrangements will come from this branch ❇️

### CODE REVIEW

File: app/components/blocks/sidebar.tsx [hunk 1]
```diff
@@ -0,0 +1,182 @@
...
+            <div className="relative">
+              <Search className="absolute left-2.5 top-2.5 h-4 w-4 text-muted-foreground" />
+              <Input
+                type="search"
+                placeholder="Search products..."
+                className="w-full appearance-none bg-background pl-8 shadow-none"
+              />
+            </div>
+          </form>
+          <nav className="grid items-start px-2 text-sm font-medium lg:px-4 gap-3">
```
Comment (liwoo) [inline app/components/blocks/sidebar.tsx:62]: you need to extract these nav items into an object, so we don't keep copy-pasting the same code

File: app/components/blocks/sidebar.tsx [hunk 2]
```diff
@@ -0,0 +1,182 @@
...
+const Sidebar = () => {
+  // TODO: fix the chevron direction on the collapsible
+  const [chevronUp, setChevronUp] = useState<boolean>(true);
+
+  return (
+    <div className="hidden bg-muted/40 md:block">
+      <div className="flex h-full m-4 mt-0 border bg-card rounded-md max-h-screen flex-col gap-2">
+        <div className="flex h-14 items-center border-b px-4 lg:h-[60px] lg:px-6">
+          <Link to="/" className="flex items-center gap-2 font-semibold">
+            <img src="./famcon-logo.png" className="size-10" />
```
Comment (liwoo) [inline app/components/blocks/sidebar.tsx:43]: check the comment below and fix it

File: app/components/blocks/some-table.tsx [hunk 3]
```diff
@@ -0,0 +1,143 @@
...
+  TableHead,
+  TableHeader,
+  TableRow,
+} from "@/components/ui/table";
+import { Badge } from "../ui/badge";
+
+const SomeTable = () => {
+  return (
+    <Table>
+      <TableHeader>
```
Comment (liwoo) [inline app/components/blocks/some-table.tsx]: again, extract the table information into a separate object and simply loop through it in your code to avoid duplication

File: app/components/layouts/header.tsx [hunk 4]
```diff
@@ -0,0 +1,180 @@
...
+              to="#"
+              className="mx-[-0.65rem] flex items-center gap-4 rounded-xl px-3 py-2 text-muted-foreground hover:text-foreground"
+            >
+              <Home className="h-5 w-5" />
+              Dashboard
+            </Link>
+            <Link
+              to="#"
+              className="mx-[-0.65rem] flex items-center gap-4 rounded-xl bg-muted px-3 py-2 text-foreground hover:text-foreground"
+            >
```
Comment (liwoo) [inline app/components/layouts/header.tsx]: same comment about extracting objects here

File: app/components/blocks/layout-header.tsx [hunk 5]
```diff
@@ -0,0 +1,91 @@
...
+} from "@/components/ui/dropdown-menu";
+import { useHydrated } from "remix-utils/use-hydrated";
+import { useCallback, useState } from "react";
+import {
+  getTheme,
+  setTheme as setSystemTheme,
+} from "@/components/theme-switcher";
+
+interface LayoutHeaderProps {
+  title?: String;
```
Comment (liwoo) [inline app/components/blocks/layout-header.tsx]: replace `String` with `string` here

**Review by liwoo — CHANGES_REQUESTED** [review]
Please pay attention to the CI/CD errors. A lot of them are actually useful.

Also never close issues until their corresponding PRs have been merged. 

You can tag an issue(s) to a PR as explained [here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests)

**Review by liwoo — APPROVED** [review]

**Comment by liwoo** [comment]
@glenmiracle18 this is approved, jsut fix the code quality issue highlighted in CI/CD

**Comment by glenmiracle18** [comment]
> @glenmiracle18 this is approved, jsut fix the code quality issue highlighted in CI/CD

on it

**Comment by glenmiracle18** [comment]
> Please pay attention to the CI/CD errors. A lot of them are actually useful.
> 
> Also never close issues until their corresponding PRs have been merged.
> 
> You can tag an issue(s) to a PR as explained [here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests)

Hello sir, 
I just tag the PR to the issues I'm resolving.
I'll be on the watch for CI/CD errors
